default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: db_atask

test:
  <<: *default
  database: db_atask

production:
  <<: *default
  database: your_app_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
